services:
  symfony-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony-linux
    working_dir: /var/www/symfony
    command:
      - tail
      - -f
      - /dev/null
    environment:
      COMPOSER_ALLOW_SUPERUSER: "1"
    volumes:
      - type: bind
        source: .
        target: /var/www/symfony
        bind:
          create_host_path: true
    ports:
      - mode: ingress
        target: 8000
        published: "8000"
        protocol: tcp
    depends_on:
      mysql:
        condition: service_started
        required: true
    networks:
      symfony-network: null

  mysql:
    image: mysql:8.0
    container_name: mysql_sym
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_DATABASE: spotifyDB
    volumes:
      - type: bind
        source: ./NoelProyectoSymfony/dataMYSQL
        target: /var/lib/mysql
        bind:
          create_host_path: true
    ports:
      - mode: ingress
        target: 3306
        published: "3306" 
        protocol: tcp
    networks:
      symfony-network: null

networks:
  symfony-network:
    name: symfonyproyectos_symfony-network
    driver: bridge
